### ISSUE TITLE
module 'select' has no attribute 'poll'

### ISSUE THREAD

**Issue by feature09** [andreikop/python-ws-discovery#30] opened 2019-11-19 02:02 UTC
I used the code in the example.
I'm runing it in windows10, and it's wrong:

```
Traceback (most recent call last):
  File "D:/PycharmProjects/ScoketDemo/UDP组播/test.py", line 13, in <module>
    wsd.start()
  File "C:\Python36\lib\site-packages\wsdiscovery\daemon.py", line 468, in start
    self._startThreads()
  File "C:\Python36\lib\site-packages\wsdiscovery\daemon.py", line 492, in _startThreads
    self._networkingThread = NetworkingThread(self)
  File "C:\Python36\lib\site-packages\wsdiscovery\daemon.py", line 97, in __init__
    self._poll = select.poll()
AttributeError: module 'select' has no attribute 'poll'
```

**Comment by andreikop** [comment] 2019-11-19 12:50
Duplicate of #1

**Closed by andreikop** 2019-11-19 12:50 UTC
